# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      uses: py-actions/flake8@v1
      with:
        ignore: "F821,E303,E501,F401,E302,E122,E123,E203,E231,E226,E251,E126,E305,E225,E402,E135,F811,E128,E121"
        exclude: "env"
        max-line-length: "150"

    - name: Deploy django to heroku
      uses: nyakaz73/heroku-django-deploy@v0.68
      with:
        heroku_app_name : ${{'rcoicourse'}}
        heroku_api_key: ${{'ec95e55c-2ee8-493e-b9c7-626c86e20565'}}
        heroku_email_address: 'eias778@gmail.com'
        use_git: true

        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        ## exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
